package com.example.quizgame;

public final class QuestionBank {

    public final static QuestionInfo[][] questions = {
            /* Grade 1 Questions */
            {
                    new QuestionInfo("Nathan and his four friends are going skating on the Rideau Canal. How many ice skates will they need all together?",
                            "Math",
                            new String[] {"10", "ten"}),
                    new QuestionInfo("True or False: The Hindu New Year's festival of lights is called Passover.",
                            "Social Studies",
                            new String[] {"False"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("What is the name of the spinning top used to play children's games during Hanukkah?",
                            "Social Studies",
                            new String[] {"dreidel"}),
                    new QuestionInfo("Which animal is not part of the cat family?",
                            "Life Systems",
                            new String[] {"Bear"},
                            "Lion",
                            "Tiger",
                            "Bear",
                            "Leopard"),
                    new QuestionInfo("What main form of energy does a television use?",
                            "Science",
                            new String[] {"electricity"}),
                    new QuestionInfo("Which month has 31 days?",
                            "Social Studies",
                            new String[] {"May"},
                            "May",
                            "June",
                            "September",
                            "November"),
                    new QuestionInfo("True or False: All adult kangaroos have pouches.",
                            "Life Systems",
                            new String[] {"False"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("The sun is primarily made of which substance?",
                            "Science",
                            new String[] {"Gas"},
                            "Gas",
                            "Molten Metal",
                            "Rock",
                            "Plasma"),
                    new QuestionInfo("Who is the author of 'The Paper Bag Princess' and 'Mortimer'?",
                            "Literature",
                            new String[] {"Robert Munsch"},
                            "Robert Munsch",
                            "R.L. Stein",
                            "J.K. Rowling",
                            "Sheila McGraw"),
                    new QuestionInfo("Hockey pucks come in boxes of 10. How many pucks are in four boxes?",
                            "Math",
                            new String[] {"40", "forty"}),
                    new QuestionInfo("Which word in the following sentence is incorrect: 'Michael went two the Pacific National Exhibition on Saturday.'",
                            "Grammar",
                            new String[] {"two"}),
                    new QuestionInfo("What is the next note in this scale? Do, Re, Mi, ...",
                            "Music",
                            new String[] {"Fa"}),
                    new QuestionInfo("True or False: A battery is something that stores and supplies energy.",
                            "Science",
                            new String[] {"True"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("Which primary colour is on the Canadian flag?",
                            "Art",
                            new String[] {"red"}),
                    new QuestionInfo("The words 'Fee Fie Foe Fum' are spoken in the fairy tale...",
                            "Literature",
                            new String[] {"Jack and the Beanstalk"},
                            "Little Red Riding Hood",
                            "Jack and the Beanstalk",
                            "Cinderella",
                            "Hansel and Gretel"),
                    new QuestionInfo("Sunflowers grow from seeds. What do tulips grow from?",
                            "Life Systems",
                            new String[] {"bulbs", "bulb"}),
                    new QuestionInfo("What shape is a stop sign?",
                            "Geometry",
                            new String[] {"octagon"}),
                    new QuestionInfo("True or False: The word 'stern' refers to the front of the boat.",
                            "Vocabulary",
                            new String[] {"False"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("Which of the world's major oceans lies directly east of Africa?",
                            "World Geography",
                            new String[] {"Indian Ocean", "Indian"}),
                    new QuestionInfo("The plural of 'moose' is __________.",
                            "Vocabulary",
                            new String[] {"moose"})

            },

            /* Grade 2 Questions */
            {
                    new QuestionInfo("What continent is France on?",
                            "World Geography",
                            new String[] {"Europe"}),
                    new QuestionInfo("Fill in the missing letters to spell out a Canadian province: Sas__________an",
                            "Spelling",
                            new String[] {"katchew"}),
                    new QuestionInfo("Which Canadian poet wrote 'Alligator Pie' and 'Garbage Delight'?",
                            "Literature",
                            new String[] {"Dennis Lee"}),
                    new QuestionInfo("How many continents are there in the world?",
                            "World Geography",
                            new String[] {"7"},
                            "5",
                            "6",
                            "7",
                            "8"),
                    new QuestionInfo("What is the root word of 'merriment'?",
                            "Vocabulary",
                            new String[] {"Merry"}),
                    new QuestionInfo("Which country is not in North America?",
                            "World Geography",
                            new String[] {"Chile"},
                            "Canada",
                            "Mexico",
                            "United States",
                            "Chile"),
                    new QuestionInfo("What is the capital city of France?",
                            "World Geography",
                            new String[] {"Paris"}),
                    new QuestionInfo("How many syllables are in the word 'elementary'?",
                            "Spelling",
                            new String[] {"5", "five", "5 syllables", "five syllables"}),
                    new QuestionInfo("'Active', 'busy', and 'occupied' are antonyms of which word?",
                            "Vocabulary",
                            new String[] {"idle"},
                            "idle",
                            "industrious",
                            "quiet",
                            "fast"),
                    new QuestionInfo("True or False: Turbines help change the energy of moving water into electrical energy.",
                            "Science",
                            new String[] {"True"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("What holiday is celebrated on the first Monday in September?",
                            "Social Studies",
                            new String[] {"Labour Day"},
                            "Simcoe Day",
                            "Labour Day",
                            "Canada Day",
                            "Victoria Day"),
                    new QuestionInfo("True or False: A deer's coat changes to adapt to different seasons.",
                            "Science",
                            new String[] {"True"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("Taylor is meeting a friend at the West Edmonton Mall at 11.45 am, but she's running 20 minutes late. What time does Taylor arrive to meet her friend?",
                            "Measurement",
                            new String[] {"12.05", "12.05 pm", "12.05pm", "12:05", "12:05 pm", "12:05pm"}),
                    new QuestionInfo("True or False: Bats are mammals.",
                            "Life Systems",
                            new String[] {"True"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("92 cans of food are collected for the school food drive. If they are stacked in pyramids of 10, how many pyramids of canned food can they build?",
                            "Math",
                            new String[] {"9", "nine"}),
                    new QuestionInfo("During Hanukkah, one candle is lit each night for 8 nights in a ...",
                            "Social Studies",
                            new String[] {"Menorah"},
                            "Menorah",
                            "Gelt",
                            "Kippah",
                            "Latke"),
                    new QuestionInfo("If 1 dog year is equal to 7 human years, how old is Rachel's 3-year-old dog Spot?",
                            "Math",
                            new String[] {"21", "21 years", "21 years old", "twenty one", "twenty one years", "twenty one years old", "twenty-one", "twenty-one years", "twenty-one years old"}),
                    new QuestionInfo("What famous Canadian founded the Marathon of Hope?",
                            "Canadian History",
                            new String[] {"Terry Fox"},
                            R.drawable.terry),
                    new QuestionInfo("The names of how many colours in the rainbow spectrum are spelled with only three letters?",
                            "Spelling",
                            new String[] {"1", "one"}),
                    new QuestionInfo("Excluding Antarctica, which continent reaches the farthest south?",
                            "World Geography",
                            new String[] {"South America"})
            },

            /* Grade 3 Questions */
            {
                    new QuestionInfo("Who was the female artist from the west coast of Canada most often associated with the group of Seven?",
                            "Art",
                            new String[] {"Emily Carr"}),
                    new QuestionInfo("The roots of a Douglas Fir tree...",
                            "Life Systems",
                            new String[] {"absorb water and nutrients"},
                            "are always green",
                            "produce seeds",
                            "absorb water and nutrients",
                            "defend against threats"),
                    new QuestionInfo("If each side of an octagon is 1 centimetre long, what is the perimeter of the octagon?",
                            "Geometry",
                            new String[] {"8 centimetres", "8 centimeters", "8 cm", "8 cm.", "8", "eight centimetres", "eight centimeters", "eight cm.", "eight cm", "eight"}),
                    new QuestionInfo("On what island is Iqaluit located?",
                            "Canadian Geography",
                            new String[] {"Baffin Island"},
                            "Prince Edward Island",
                            "Baffin Island",
                            "Queen Island",
                            "Vancouver Island"),
                    new QuestionInfo("What does the abbreviation 'P.S.' stand for?",
                            "Spelling",
                            new String[] {"post script"}),
                    new QuestionInfo("The 3 main kinds of rock pieces found in soil are clay, sand, and __________.",
                            "Earth and Space Systems",
                            new String[] {"silt"},
                            "dirt",
                            "gravel",
                            "silt",
                            "carbon"),
                    new QuestionInfo("What type of song is 'O Canada'?",
                            "Music",
                            new String[] {"national anthem"}),
                    new QuestionInfo("True or False: A.Y. Jackson was a member of the Group of Seven.",
                            "Art",
                            new String[] {"True"},
                            "True",
                            "False",
                            "",
                            ""),
                    new QuestionInfo("Which province's name comes from the Cree word that means 'swift-river flowing'?",
                            "Canadian History",
                            new String[] {"Saskatchewan"}),
                    new QuestionInfo("How many months old is Jacob's little sister if she is 2.5 years old?",
                            "Math",
                            new String[] {"30", "thirty", "30 months", "thirty months", "30 months old", "thirty months old"}),
                    new QuestionInfo("What is the main area of study at an arboretum?",
                            "Vocabulary",
                            new String[] {"trees", "tree"}),
                    new QuestionInfo("Who wrote the poem 'In Flanders Fields'?",
                            "Literature",
                            new String[] {"John McCrae"}),
                    new QuestionInfo("The True North Pole is located in the middle of which group of islands?",
                            "Canadian Geography",
                            new String[] {"Queen Elizabeth Islands"},
                            "Thousand Islands",
                            "Queen Elizabeth Islands",
                            "Queen Charlotte Islands",
                            "Gulf Islands"),
                    new QuestionInfo("What is the abstract noun in this sentence? 'Isiah went to the legislature to learn about democracy.'",
                            "Grammar",
                            new String[] {"democracy"}),
                    new QuestionInfo("In what month is Saint-Jean-Baptiste Day celebrated in Quebec?",
                            "Social Studies",
                            new String[] {"June"}),
                    new QuestionInfo("In what town was the book 'Anne of Green Gables' set?",
                            "Literature",
                            new String[] {"Cavendish"}),
                    new QuestionInfo("What is the longest river in the world?",
                            "World Geography",
                            new String[] {"Nile River", "Nile"}),
                    new QuestionInfo("What unit of power is abbreviated by the letter 'W'?",
                            "Measurement",
                            new String[] {"watt"}),
                    new QuestionInfo("The Roman numeral XXIX represents what number?",
                            "Measurement",
                            new String[] {"29", "twenty nine", "twenty-nine"}),
                    new QuestionInfo("The equator intersects what other imaginary line at zero degrees latitude, zero degrees longitude?",
                            "World Geography",
                            new String[] {"Prime Meridian", "The Prime Meridian"})
            },

            /* Grade 4 Questions */
            {
                    new QuestionInfo("What is the French translation of 'I am tired'?",
                            "French",
                            new String[] {"Je suis fatigué", "Je suis fatiguée", "Je suis fatigue", "Je suis fatiguee"}),
                    new QuestionInfo("A structure is built to hold a load. What is the load of a car called?",
                            "Science",
                            new String[] {"chassis"}),
                    new QuestionInfo("What do the last three letters in 'R.S.V.P.' stand for?",
                            "French",
                            new String[] {"s'il vous plaît", "s'il vous plait"}),
                    new QuestionInfo("What is the present tense of the 'vous' form of the verb 'FAIRE'?",
                            "French",
                            new String[] {"vous faites", "faites"}),
                    new QuestionInfo("Which Canadian invented basketball?",
                            "Social Studies",
                            new String[] {"James Naismith", "Naismith"},
                            R.drawable.naismith),
                    new QuestionInfo("What is the southernmost point of Canada's mainland?",
                            "Canadian Geography",
                            new String[] {"Point Pelee"}),
                    new QuestionInfo("Near what Alberta town were hundreds of dinosaur skeletons discovered?",
                            "Canadian Geography",
                            new String[] {"Drumheller"}),
                    new QuestionInfo("At what UNESCO world heritage site were bison hunted by being forced to jump over cliffs?",
                            "Canadian History",
                            new String[] {"Head-Smashed-In Buffalo Jump", "Head Smashed In Buffalo Jump", "Buffalo Jump"}),
                    new QuestionInfo("What is the name of the symbol which appears on the Quebec flag four times?",
                            "French",
                            new String[] {"fleur-de-lis", "fleur-de-lys", "fleur de lis", "fleur de lys"},
                            R.drawable.quebec_flag),
                    new QuestionInfo("'The Jack Pine' and 'The West Wind' were painted by what Canadian artist?",
                            "Art",
                            new String[] {"Tom Thomson", "Thomas Thomson"}),
                    new QuestionInfo("Costa Rica borders two countries: Nicaragua and __________.",
                            "World Geography",
                            new String[] {"Panama"}),
                    new QuestionInfo("What is the capital of Brazil?",
                            "World Geography",
                            new String[] {"Brasilia"}),
                    new QuestionInfo("What was the ancient Egyptian writing system called?",
                            "World History",
                            new String[] {"Hieroglyphs", "Hieroglyphics"},
                            R.drawable.hieroglyphs),
                    new QuestionInfo("In a right triangle, the side opposite the right angle is called the what?",
                            "Geometry",
                            new String[] {"Hypotenuse"},
                            "Base",
                            "Hypotenuse",
                            "Radius",
                            "Tangent"),
                    new QuestionInfo("If you're traveling due southeast and make a 180 degree turn, what direction are you now heading?",
                            "Measurement",
                            new String[] {"northwest"}),
                    new QuestionInfo("How many hours of direct sunlight does the South Pole receive on June 21st?",
                            "Earth and Space Systems",
                            new String[] {"zero"},
                            "zero",
                            "twenty",
                            "thirty",
                            "ten"),
                    new QuestionInfo("Lightning is what type of electricity?",
                            "Science",
                            new String[] {"static"},
                            "current",
                            "alternating",
                            "static",
                            "direct"),
                    new QuestionInfo("Which blood type is known as the universal recipient?",
                            "Life Systems",
                            new String[] {"AB"},
                            "A",
                            "O",
                            "AB",
                            "B"),
                    new QuestionInfo("Which of the following terms refers to the relative speed of a piece of music?",
                            "Music",
                            new String[] {"Tempo"},
                            "Staccato",
                            "Mezzo",
                            "Tempo",
                            "Vivace"),
                    new QuestionInfo("Who became the first chairman of the People's Republic of China in 1949?",
                            "World History",
                            new String[] {"Mao Zedong", "Mao Ze Dong", "Zedong Mao", "Ze Dong Mao", "Mao"})
            },

            /* Grade 5 Questions */
            {
                    new QuestionInfo("What is a triangle called with no equal sides and no equal angles?",
                            "Geometry",
                            new String[] {"scalene"}),
                    new QuestionInfo("What is the scientific name for the body part called windpipe?",
                            "Life Systems",
                            new String[] {"trachea"}),
                    new QuestionInfo("What is the term for two lines that intersect at a right angle?",
                            "Geometry",
                            new String[] {"perpendicular"},
                            R.drawable.perpendicular),
                    new QuestionInfo("What are the three colours on Belgium's flag?",
                            "World Geography",
                            new String[] {"Red, Yellow, Black"},
                            "Red, Orange, Black",
                            "Orange, Yellow, Black",
                            "Red, Orange, Yellow",
                            "Red, Yellow, Black"),
                    new QuestionInfo("Michael's swimming pool is 3 metres wide, 6 metres long, and 2 metres deep. How much water, in litres, will he need to fill it?",
                            "Measurement",
                            new String[] {"36000", "36,000", "36000 litres", "36000 liters", "36,000 litres", "36,000 liters"}),
                    new QuestionInfo("Who developed the scale of mineral hardness?",
                            "Measurement",
                            new String[] {"Friedrich Mohs", "Mohs"}),
                    new QuestionInfo("Which of the following is NOT an official language of Switzerland?",
                            "Social Studies",
                            new String[] {"Spanish"},
                            "German",
                            "Italian",
                            "Spanish",
                            "French"),
                    new QuestionInfo("What is the name of this painting by Norwegian artist Edvard Munch?",
                            "Art",
                            new String[] {"The Scream", "Scream"},
                            R.drawable.scream),
                    new QuestionInfo("Charles Lindbergh flew the first solo nonstop transatlantic flight from New York to what city?",
                            "World History",
                            new String[] {"Paris"}),
                    new QuestionInfo("What Communist leader is shown in this picture?",
                            "World History",
                            new String[] {"Nikita Khrushchev", "Khrushchev"},
                            R.drawable.khrushchev),
                    new QuestionInfo("You collect 48 pieces of Halloween candy. Your parents say you can eat 2 pieces per day, plus an extra piece on Saturdays and Sundays. How many weeks will it take to finish all of your candy?",
                            "Math",
                            new String[] {"3 weeks", "3"}),
                    new QuestionInfo("Buenos Aires is the capital and largest city of what South American country?",
                            "World Geography",
                            new String[] {"Argentina"}),
                    new QuestionInfo("Roland has a box of 35 red and green candles. If the ratio of red to green is 3 to 4, how many green candles are there?",
                            "Math",
                            new String[] {"20", "twenty", "20 candles", "twenty candles", "20 green candles", "twenty green candles"}),
                    new QuestionInfo("If you traveled two decametres and a hectometre, how many metres would you have gone?",
                            "Measurement",
                            new String[] {"120", "120 metres", "120 meters", "one hundred twenty", "one hundred and twenty", "one hundred twenty metres", "one hundred twenty meters", "one hundred and twenty metres", "one hundred and twenty meters"}),
                    new QuestionInfo("What is the most abundant element in the universe?",
                            "Science",
                            new String[] {"Hydrogen"}),
                    new QuestionInfo("There are three basic types of muscle tissue in the human body: smooth, skeletal, and __________.",
                            "Life Systems",
                            new String[] {"cardiac"}),
                    new QuestionInfo("At room temperature, approximately 20 degrees Celsius, two elements on the periodic table exist in a liquid state: Bromine and __________.",
                            "Science",
                            new String[] {"Mercury"}),
                    new QuestionInfo("Russia's longest land border is with what other country?",
                            "World Geography",
                            new String[] {"Kazakhstan"}),
                    new QuestionInfo("The League of Nations was formed at the conclusion of what war?",
                            "World History",
                            new String[] {"World War I", "World War 1", "World War One", "First World War"}),
                    new QuestionInfo("Mount Everest is located in which mountain range?",
                            "World Geography",
                            new String[] {"Himalayas", "The Himalayas", "Himalayan Mountains", "Himalaya"}),
                    new QuestionInfo("'Two households, both alike in dignity' is the opening line to what Shakespearean play?",
                            "Drama",
                            new String[] {"Romeo and Juliet", "Romeo & Juliet"})
            }
    };

}
